version: '3.3'

services:
  mysql:
    image: mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: njimko0
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always

  wordpress:
    build:
      context: ./wp-build
    image: wp:nitemare
    ports:
      - '9000:9000'
    volumes:
      - ./html:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: always

  www:
    image: nginx
    volumes:
      - ./html:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    links:
      - wordpress
      
  adminer:
    image: adminer
    restart: always
    links:
      - mysql
    ports:
      - 8080:8080

